# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 559)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarAddExpense = QtWidgets.QCalendarWidget(self.tab)
        self.calendarAddExpense.setGridVisible(True)
        self.calendarAddExpense.setObjectName("calendarAddExpense")
        self.gridLayout.addWidget(self.calendarAddExpense, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.valueAddExpense = QtWidgets.QLineEdit(self.tab)
        self.valueAddExpense.setObjectName("valueAddExpense")
        self.gridLayout.addWidget(self.valueAddExpense, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.descriptionAddExpense = QtWidgets.QLineEdit(self.tab)
        self.descriptionAddExpense.setObjectName("descriptionAddExpense")
        self.gridLayout.addWidget(self.descriptionAddExpense, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.categoryAddExpense = QtWidgets.QComboBox(self.tab)
        self.categoryAddExpense.setObjectName("categoryAddExpense")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.categoryAddExpense.addItem("")
        self.gridLayout.addWidget(self.categoryAddExpense, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.accountAddExpense = QtWidgets.QComboBox(self.tab)
        self.accountAddExpense.setObjectName("accountAddExpense")
        self.accountAddExpense.addItem("")
        self.accountAddExpense.addItem("")
        self.accountAddExpense.addItem("")
        self.accountAddExpense.addItem("")
        self.accountAddExpense.addItem("")
        self.gridLayout.addWidget(self.accountAddExpense, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.observationsAddExpense = QtWidgets.QTextEdit(self.tab)
        self.observationsAddExpense.setObjectName("observationsAddExpense")
        self.gridLayout.addWidget(self.observationsAddExpense, 3, 1, 1, 3)
        self.confirmBtnAddExpense = QtWidgets.QPushButton(self.tab)
        self.confirmBtnAddExpense.setObjectName("confirmBtnAddExpense")
        self.gridLayout.addWidget(self.confirmBtnAddExpense, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.calendarAddIncome = QtWidgets.QCalendarWidget(self.tab_2)
        self.calendarAddIncome.setGridVisible(True)
        self.calendarAddIncome.setObjectName("calendarAddIncome")
        self.gridLayout_3.addWidget(self.calendarAddIncome, 0, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.valueAddIncome = QtWidgets.QLineEdit(self.tab_2)
        self.valueAddIncome.setObjectName("valueAddIncome")
        self.gridLayout_3.addWidget(self.valueAddIncome, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1)
        self.descriptionAddIncome = QtWidgets.QLineEdit(self.tab_2)
        self.descriptionAddIncome.setObjectName("descriptionAddIncome")
        self.gridLayout_3.addWidget(self.descriptionAddIncome, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.categoryAddIncome = QtWidgets.QComboBox(self.tab_2)
        self.categoryAddIncome.setObjectName("categoryAddIncome")
        self.categoryAddIncome.addItem("")
        self.gridLayout_3.addWidget(self.categoryAddIncome, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.observationsAddIncome = QtWidgets.QTextEdit(self.tab_2)
        self.observationsAddIncome.setObjectName("observationsAddIncome")
        self.gridLayout_3.addWidget(self.observationsAddIncome, 3, 1, 1, 3)
        self.confirmBtnAddIncome = QtWidgets.QPushButton(self.tab_2)
        self.confirmBtnAddIncome.setObjectName("confirmBtnAddIncome")
        self.gridLayout_3.addWidget(self.confirmBtnAddIncome, 4, 3, 1, 1)
        self.accountAddIncome = QtWidgets.QComboBox(self.tab_2)
        self.accountAddIncome.setObjectName("accountAddIncome")
        self.accountAddIncome.addItem("")
        self.accountAddIncome.addItem("")
        self.accountAddIncome.addItem("")
        self.accountAddIncome.addItem("")
        self.accountAddIncome.addItem("")
        self.gridLayout_3.addWidget(self.accountAddIncome, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDevelopment_Tool = QtWidgets.QAction(MainWindow)
        self.actionDevelopment_Tool.setObjectName("actionDevelopment_Tool")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDevelopment_Tool)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My Project"))
        self.label.setText(_translate("MainWindow", "Value"))
        self.label_3.setText(_translate("MainWindow", "Description"))
        self.label_2.setText(_translate("MainWindow", "Category"))
        self.categoryAddExpense.setItemText(0, _translate("MainWindow", "Car Expenses"))
        self.categoryAddExpense.setItemText(1, _translate("MainWindow", "Dad\'s Expenses"))
        self.categoryAddExpense.setItemText(2, _translate("MainWindow", "Eletronics"))
        self.categoryAddExpense.setItemText(3, _translate("MainWindow", "Fix Expenses"))
        self.categoryAddExpense.setItemText(4, _translate("MainWindow", "Games"))
        self.categoryAddExpense.setItemText(5, _translate("MainWindow", "Gifts"))
        self.categoryAddExpense.setItemText(6, _translate("MainWindow", "Restaurants"))
        self.categoryAddExpense.setItemText(7, _translate("MainWindow", "Supermarket"))
        self.label_4.setText(_translate("MainWindow", "Account"))
        self.accountAddExpense.setItemText(0, _translate("MainWindow", "Cash"))
        self.accountAddExpense.setItemText(1, _translate("MainWindow", "Checking Account"))
        self.accountAddExpense.setItemText(2, _translate("MainWindow", "Credit Card"))
        self.accountAddExpense.setItemText(3, _translate("MainWindow", "Dad\'s Account"))
        self.accountAddExpense.setItemText(4, _translate("MainWindow", "Savings Account"))
        self.label_5.setText(_translate("MainWindow", "Observations"))
        self.confirmBtnAddExpense.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Add Expense"))
        self.label_10.setText(_translate("MainWindow", "Value"))
        self.label_6.setText(_translate("MainWindow", "Description"))
        self.label_8.setText(_translate("MainWindow", "Category"))
        self.categoryAddIncome.setItemText(0, _translate("MainWindow", "Salary"))
        self.label_9.setText(_translate("MainWindow", "Account"))
        self.label_7.setText(_translate("MainWindow", "Observations"))
        self.confirmBtnAddIncome.setText(_translate("MainWindow", "Confirm"))
        self.accountAddIncome.setItemText(0, _translate("MainWindow", "Cash"))
        self.accountAddIncome.setItemText(1, _translate("MainWindow", "Checking Account"))
        self.accountAddIncome.setItemText(2, _translate("MainWindow", "Credit Card"))
        self.accountAddIncome.setItemText(3, _translate("MainWindow", "Dad\'s Savings"))
        self.accountAddIncome.setItemText(4, _translate("MainWindow", "Savings Account"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add Income"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionDevelopment_Tool.setText(_translate("MainWindow", "Development Tool"))
        self.actionDevelopment_Tool.setShortcut(_translate("MainWindow", "F10"))

